# Generated by Django 4.1.6 on 2023-02-04 23:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='added',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 2, 4, 23, 9, 20, 339777, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(upload_to='estate/static/media'),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
