# Generated by Django 4.1.6 on 2023-02-05 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_alter_house_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 2, 5, 0, 18, 13, 398899, tzinfo=datetime.timezone.utc), upload_to='static/media'),
            preserve_default=False,
        ),
    ]
