# Generated by Django 4.1.6 on 2023-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_alter_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bed_rooms',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='living_rooms',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='parking',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
