# Generated by Django 4.1.6 on 2023-02-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_house_bed_rooms_house_kitchen_house_living_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='listing',
            field=models.CharField(choices=[('os', 'office space'), ('ap', 'apartment'), ('hs', 'house')], default='ap', max_length=2),
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('by', 'buy'), ('sl', 'sale'), ('rt', 'rent')], default='rt', max_length=2),
        ),
    ]
