# Generated by Django 4.1.6 on 2023-02-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_house_listing_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(upload_to='static/images/slider'),
        ),
    ]
