# Generated by Django 4.1.6 on 2023-02-08 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0016_remove_house_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='user',
        ),
    ]
